import { cookies } from "next/headers";

import { APP_ROLES, type AppRole } from "@/db/schema";
import { permissionsForRole, roleHasPermission, type Permission } from "./roles";

export const ROLE_COOKIE = "ctl_role";
const DEFAULT_ROLE: AppRole = "admin";

/**
 * Demo identities for the prototype. Each role maps to a representative user so
 * audit logs and "generated by" fields are populated without real auth.
 */
const DEMO_USERS: Record<AppRole, { id: string; name: string; email: string }> =
  {
    admin: {
      id: "user-admin",
      name: "Avery Admin",
      email: "avery.admin@twogood.example",
    },
    impact_analyst: {
      id: "user-impact",
      name: "Imogen Impact",
      email: "imogen.impact@twogood.example",
    },
    ops: {
      id: "user-ops",
      name: "Olivia Ops",
      email: "olivia.ops@twogood.example",
    },
    viewer: {
      id: "user-viewer",
      name: "Vic Viewer",
      email: "vic.viewer@twogood.example",
    },
  };

export type CurrentUser = {
  id: string;
  name: string;
  email: string;
  role: AppRole;
  permissions: Permission[];
};

function isAppRole(value: string | undefined): value is AppRole {
  return !!value && (APP_ROLES as readonly string[]).includes(value);
}

export async function getCurrentUser(): Promise<CurrentUser> {
  const store = await cookies();
  const cookieRole = store.get(ROLE_COOKIE)?.value;
  const role: AppRole = isAppRole(cookieRole) ? cookieRole : DEFAULT_ROLE;
  const profile = DEMO_USERS[role];
  return {
    ...profile,
    role,
    permissions: permissionsForRole(role),
  };
}

export async function can(permission: Permission): Promise<boolean> {
  const user = await getCurrentUser();
  return roleHasPermission(user.role, permission);
}

/**
 * Throws when the active role lacks the required permission. Used to guard
 * server actions and route handlers that mutate data.
 */
export async function requirePermission(
  permission: Permission
): Promise<CurrentUser> {
  const user = await getCurrentUser();
  if (!roleHasPermission(user.role, permission)) {
    throw new Error(
      `Your role (${user.role}) is not permitted to perform this action.`
    );
  }
  return user;
}
